-- The tasks example module (apps/api/src/modules/tasks).
--   id       nanoid, 21 chars, generated by the application
--   version  optimistic-lock counter: every UPDATE checks and bumps it
CREATE TABLE tasks (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT,
  status      TEXT NOT NULL CHECK (status IN ('ACTIVE', 'ARCHIVED')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  version     INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX tasks_status_created_at_idx ON tasks (status, created_at DESC);
