-- The tasks example module (apps/api/src/modules/tasks).
--   id       nanoid, 21 chars, generated by the application
--   version  optimistic-lock counter: every UPDATE checks and bumps it
CREATE TABLE tasks (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT,
  status      TEXT NOT NULL CHECK (status IN ('ACTIVE', 'ARCHIVED')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  version     INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX tasks_status_created_at_idx ON tasks (status, created_at DESC);

-- Transactional outbox (@base/outbox): a row is written in the same
-- transaction as the state change it announces, and deleted once the relay
-- has published it to Kafka. A row whose send keeps failing is retried
-- OUTBOX_MAX_ATTEMPTS times (attempts, last_error), then left here for an
-- operator instead of blocking the batch.
CREATE TABLE outbox (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  topic      TEXT NOT NULL,
  key        TEXT,
  payload    JSONB NOT NULL,
  -- W3C trace context + x-request-id of the writing request, sent as record headers
  headers    JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  attempts   INT NOT NULL DEFAULT 0,
  last_error TEXT
);

-- Idempotency-Key results when the api runs without Valkey
-- (@base/idempotency PgIdempotencyStore). An expired row is dead: reads skip
-- it, the next insert of its key replaces it, inserts prune a few each.
CREATE TABLE idempotency_keys (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idempotency_keys_expires_at ON idempotency_keys (expires_at);
