// Generated by api/scripts/event-types.mjs from api/jsonschema — do not edit; run `just contracts`.

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Published to the `tasks.events` topic when a task is created; record key = task id. */
        TaskCreatedEvent: {
            /**
             * @description Event type; one topic may carry several.
             * @constant
             */
            type: "task.created";
            /** @description The task's id (also the record key). */
            id: components["schemas"]["TaskId"];
            /** @description Title at creation time. */
            title: string;
            /**
             * Format: date-time
             * @description Creation time, RFC 3339 UTC.
             */
            createdAt: string;
        };
        /**
         * @description Server-assigned task identifier: a 21-character nanoid over the URL-safe
         *     alphabet (generated at the application layer by packages/common `generateId`).
         */
        TaskId: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
