// Generated by api/scripts/event-types.mjs from api/jsonschema — do not edit; run `just contracts`.

export const eventSchemas = {
  "TaskCreatedEvent": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "TaskCreatedEvent.json",
    "type": "object",
    "properties": {
      "type": {
        "type": "string",
        "const": "task.created",
        "description": "Event type; one topic may carry several."
      },
      "id": {
        "$ref": "#/$defs/TaskId",
        "description": "The task's id (also the record key)."
      },
      "title": {
        "type": "string",
        "description": "Title at creation time."
      },
      "createdAt": {
        "type": "string",
        "format": "date-time",
        "description": "Creation time, RFC 3339 UTC."
      }
    },
    "required": [
      "type",
      "id",
      "title",
      "createdAt"
    ],
    "description": "Published to the `tasks.events` topic when a task is created; record key = task id.",
    "$defs": {
      "TaskId": {
        "type": "string",
        "pattern": "^[A-Za-z0-9_-]{21}$",
        "description": "Server-assigned task identifier: a 21-character nanoid over the URL-safe\nalphabet (generated at the application layer by packages/common `generateId`)."
      }
    }
  }
};
