/**
 * @base/contracts — the TypeScript side of the HTTP contract.
 *
 * `tasksapi.gen.ts` is generated by openapi-typescript from
 * api/openapi3/tasks.openapi.yaml (itself emitted from api/tsp); never edit
 * it, run `just contracts`. This module re-exports the generated `paths` /
 * `components` / `operations` and names the schemas a client or a test
 * reaches for. Types only — there is nothing to import at runtime.
 */
export type { components, operations, paths } from "./tasksapi.gen.js";

import type { components } from "./tasksapi.gen.js";

type Schemas = components["schemas"];

/** A single to-do item (GET /tasks/{id}, and the body of every write). */
export type Task = Schemas["Task"];
/** Lifecycle state of a task. */
export type TaskStatus = Schemas["TaskStatus"];
/** One row of GET /tasks. */
export type TaskListItem = Schemas["TaskListItem"];
/** Body of GET /tasks. */
export type TaskListPage = Schemas["TaskListPage"];
/** Body of POST /tasks. */
export type CreateTask = Schemas["CreateTask"];
/** Body of PATCH /tasks/{id}. */
export type UpdateTask = Schemas["UpdateTask"];
/** Body of POST /tasks/{id}/archive. */
export type ArchiveTask = Schemas["ArchiveTask"];
/** RFC 9457 problem details — every error response. */
export type Problem = Schemas["Problem"];
/** Body of GET /health. */
export type HealthStatus = Schemas["HealthStatus"];
