/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Report that the API process is up. */
        get: operations["HealthOps_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List tasks, newest first, one page at a time. The query is closed like
         *     the bodies: an unknown query parameter is a 400 problem.
         */
        get: operations["TasksOps_list"];
        put?: never;
        /**
         * @description Create a task. Its `task.created` event is written in the same
         *     transaction (outbox) and reaches Kafka shortly after.
         *     409: the Idempotency-Key is in flight or was used for a different request.
         */
        post: operations["TasksOps_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch one task. */
        get: operations["TasksOps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Change title and/or description with optimistic locking. */
        patch: operations["TasksOps_update"];
        trace?: never;
    };
    "/tasks/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Archive a task (terminal: archiving an archived task is a 409 problem). */
        post: operations["TasksOps_archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body of POST /tasks/{id}/archive. Closed object. */
        ArchiveTask: {
            /**
             * Format: int32
             * @description The version the client last read — a stale value is a 409 problem.
             */
            expectedVersion: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Body of POST /tasks. Closed, like every object here (tspconfig
         *     `seal-object-schemas`): an unknown member is rejected with a 400 problem.
         */
        CreateTask: {
            title: string;
            description?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Body of GET /health — the public-side liveness of the API process.
         *     Kubernetes probes target the admin listener (/healthz, /readyz on
         *     ADMIN_PORT), not this route; it exists so a client can tell the API is up.
         */
        HealthStatus: {
            /**
             * @description Always "ok" — the process answered.
             * @enum {string}
             */
            status: "ok";
            /** @description Service name (OTEL_SERVICE_NAME; "app" when unset). */
            service: string;
            /** @description NODE_ENV of the process ("development" when unset). */
            env: string;
            /**
             * Format: int32
             * @description Whole seconds since the process started.
             */
            uptimeSeconds: number;
            /**
             * Format: date-time
             * @description Time of the answer, RFC 3339 UTC.
             */
            timestamp: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description RFC 9457 problem details. Extension members are inlined (RFC 9457 §3.2):
         *     every error the API emits carries `errorId` and `instance`, and
         *     `request_id` whenever the request had a context (always, for a route).
         */
        Problem: {
            /** @description URI reference identifying the problem type; "about:blank" for a generic HTTP error. */
            type: string;
            /** @description Short, human-readable summary of the problem type (the HTTP reason phrase for about:blank). */
            title: string;
            /**
             * Format: int32
             * @description HTTP status of this occurrence — always equals the response status.
             */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /** @description URI reference identifying this occurrence — the request path (with query). */
            instance?: string;
            /** @description Opaque id of this error occurrence, also on the server's log line (error.id). */
            errorId?: string;
            /**
             * @description The request's correlation id — the same value as the X-Request-Id
             *     response header and the http.request.id field of the service's log lines.
             */
            request_id?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description A single to-do item. */
        Task: {
            id: components["schemas"]["TaskId"];
            /** @description Human-readable title; 1..200 characters. */
            title: string;
            /** @description Longer description, up to 2000 characters; null when the task has none. */
            description: string | null;
            status: components["schemas"]["TaskStatus"];
            /**
             * Format: date-time
             * @description Creation time, RFC 3339 UTC.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Time of the last write, RFC 3339 UTC (equals createdAt until the first update).
             */
            updatedAt: string;
            /**
             * Format: int32
             * @description Optimistic-lock counter: 0 at creation, +1 on every write; sent back as `expectedVersion`.
             */
            version: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Server-assigned task identifier: a 21-character nanoid over the URL-safe
         *     alphabet (generated at the application layer by packages/common `generateId`).
         */
        TaskId: string;
        /** @description One row of GET /tasks — the list projection carries no description/version. */
        TaskListItem: {
            id: components["schemas"]["TaskId"];
            title: string;
            status: components["schemas"]["TaskStatus"];
            /** Format: date-time */
            createdAt: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Body of GET /tasks: one page, newest first, plus the total row count. */
        TaskListPage: {
            items: components["schemas"]["TaskListItem"][];
            /**
             * Format: int32
             * @description Number of tasks in the store (all pages).
             */
            total: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Lifecycle state of a task.
         * @enum {string}
         */
        TaskStatus: "ACTIVE" | "ARCHIVED";
        /**
         * @description Body of PATCH /tasks/{id}. Only the members present are changed;
         *     `description: null` clears it. `expectedVersion` is the version the client
         *     last read — a stale value is a 409 problem. Closed object.
         */
        UpdateTask: {
            title?: string;
            description?: string | null;
            /** Format: int32 */
            expectedVersion: number;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: {
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthOps_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    TasksOps_list: {
        parameters: {
            query?: {
                /** @description Rows to skip. */
                offset?: number;
                /** @description Page size; the server default (TASK_LIST_PAGE_SIZE, 50) when absent. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListPage"];
                };
            };
            /** @description A problem response with the given status and content type. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    TasksOps_create: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTask"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    /** @description "true" when the response was replayed for a repeated Idempotency-Key. */
                    "X-Idempotent-Replayed"?: "true";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description A problem response with the given status and content type. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    TasksOps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description A problem response with the given status and content type. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    TasksOps_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTask"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description A problem response with the given status and content type. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    TasksOps_archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveTask"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description A problem response with the given status and content type. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A problem response with the given status and content type. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
