// Types for the event schemas (api/jsonschema/*.json) → packages/contracts/src/events.gen.ts,
// and the schemas themselves → events.schemas.gen.ts (a consumer validates a record with them).
//
// openapi-typescript already turns the HTTP document's schemas into types;
// OpenAPI 3.1 schemas *are* JSON Schema 2020-12, so the event schemas go
// through it too, wrapped in a minimal 3.1 document (each file's $defs
// hoisted next to it) — no second generator.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const api = fileURLToPath(new URL("..", import.meta.url));
const dir = join(api, "jsonschema");
const out = join(api, "..", "packages", "contracts", "src", "events.gen.ts");
const outSchemas = join(api, "..", "packages", "contracts", "src", "events.schemas.gen.ts");

const schemas = {};
const raw = {};
const toComponents = (node) =>
  JSON.parse(JSON.stringify(node).replaceAll('"#/$defs/', '"#/components/schemas/'));
for (const file of readdirSync(dir).filter((f) => f.endsWith(".json")).toSorted()) {
  const parsed = JSON.parse(readFileSync(join(dir, file), "utf8"));
  raw[basename(file, ".json")] = parsed;
  const { $schema: _s, $id: _i, $defs = {}, ...schema } = parsed;
  schemas[basename(file, ".json")] = toComponents(schema);
  for (const [name, def] of Object.entries($defs)) schemas[name] = toComponents(def);
}

const doc = { openapi: "3.1.0", info: { title: "Events", version: "1.0.0" }, paths: {}, components: { schemas } };
const header = "// Generated by api/scripts/event-types.mjs from api/jsonschema — do not edit; run `just contracts`.\n\n";
writeFileSync(out, header + astToString(await openapiTS(doc)));
writeFileSync(outSchemas, `${header}export const eventSchemas = ${JSON.stringify(raw, null, 2)};\n`);
console.log(`event-types: ${Object.keys(schemas).join(", ")} → ${out}`);
